version: "3"
services:

  proxy:
    build:
      context: ./reverse_proxy
    depends_on:
      - api
      - authenticator
    ports:
      - "8081:80"
    restart: on-failure
    networks:
      - default

  api:
    build: ./api
    command: gunicorn -b :8000 location.wsgi:application
    depends_on:
      - authenticator
    environment:
      - DEBUG=True
      - DB_URI=postgresql://postgres:postgres@db:5432/location
      - AUTHENTICATOR_URI=http://authenticator:8000
    # ports:
    #   - "8000:8000"
    networks:
      - default
    restart: on-failure
  
  authenticator:
    build: ./authenticator
    command: gunicorn -b :8000 authenticator.wsgi:application
    environment:
      - DEBUG=True
      - DB_URI=postgresql://postgres:postgres@db-authenticator:5432/authenticator
    # ports:
    #   - "8001:8000"
    networks:
      - default
    restart: on-failure

networks:
  default:
    driver: bridge