# Generated by Django 4.1.2 on 2022-10-12 21:58

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('coordinate_x', models.PositiveIntegerField()),
                ('coordinate_y', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
